language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pandoc
script:
  - python setup.py build_ext -i
  - python -m compileall -f .
  - python setup.py test

